[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.tox]
legacy_tox_ini = '''
[tox]
envlist = py{36,37,38}
install_command = pip install {opts} "{packages}"

[testenv]
basepython =
    py36: python3.6
    py37: python3.7
    py38: python3.8

commands =
	nosetests {posargs}

deps =
    -rrequirements-test.txt
'''
